include:
- ./func/*
kind: ArchiveUploadSpec
name: func-MU8H

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: notification-count-unliste-59bed6c4-63a2-42bc-a50b-a915e60d9d10
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: notification-count-unlisted-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-MU8H
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-11-29T22:04:27Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: notification-count-unlisted-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: notification-count-unlisted-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_number_of_unlisted_notifications
    packageref:
      name: notification-count-unliste-59bed6c4-63a2-42bc-a50b-a915e60d9d10
      namespace: default
  requestsPerPod: 10000
  resources: {}
