include:
- ./func/*
kind: ArchiveUploadSpec
name: func-fAjn

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: notification-count-unliste-9cfcab37-53a4-4c29-8697-e17e91a0846f
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: notification-count-unlisted-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-fAjn
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-11-29T22:04:36Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: notification-count-unlisted-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: notification-count-unlisted-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_number_of_unlisted_notifications
    packageref:
      name: notification-count-unliste-9cfcab37-53a4-4c29-8697-e17e91a0846f
      namespace: default
  requestsPerPod: 10000
  resources: {}
